// This file was auto-generated by ML.NET Model Builder. 

using System.IO;
using Microsoft.ML;
using Microsoft.ML.Data;

namespace CollaborativeFilteringRecipeRecommendations_API
{
    public partial class CollaborativeFilteringRecipeRecommendations
    {
        /// <summary>
        ///     model input class for CollaborativeFilteringRecipeRecommendations.
        /// </summary>

        #region model input class

        public class ModelInput
        {
            [ColumnName(@"user_id")] public string User_id { get; set; }

            [ColumnName(@"recipe_id")] public string Recipe_id { get; set; }

            [ColumnName(@"rating")] public float Rating { get; set; }
        }

        #endregion

        /// <summary>
        ///     model output class for CollaborativeFilteringRecipeRecommendations.
        /// </summary>

        #region model output class

        public class ModelOutput
        {
            public float Score { get; set; }
        }

        #endregion

        private static readonly string MlNetModelPath =
            Path.GetFullPath("CollaborativeFilteringRecipeRecommendations.zip");

        /// <summary>
        ///     Use this method to predict on <see cref="ModelInput" />.
        /// </summary>
        /// <param name="input">model input.</param>
        /// <returns>
        ///     <seealso cref=" ModelOutput" />
        /// </returns>
        public static ModelOutput Predict(ModelInput input)
        {
            var mlContext = new MLContext();

            // Load model & create prediction engine
            var mlModel = mlContext.Model.Load(MlNetModelPath, out var modelInputSchema);
            var predEngine = mlContext.Model.CreatePredictionEngine<ModelInput, ModelOutput>(mlModel);

            var result = predEngine.Predict(input);
            return result;
        }
    }
}