﻿// This file was auto-generated by ML.NET Model Builder. 
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.ML.Data;
using Microsoft.ML.Trainers;
using Microsoft.ML;

namespace CollaborativeFilteringRecipeRecommendations_API
{
    public partial class CollaborativeFilteringRecipeRecommendations
    {
        public static ITransformer RetrainPipeline(MLContext context, IDataView trainData)
        {
            var pipeline = BuildPipeline(context);
            var model = pipeline.Fit(trainData);

            return model;
        }

        /// <summary>
        /// build the pipeline that is used from model builder. Use this function to retrain model.
        /// </summary>
        /// <param name="mlContext"></param>
        /// <returns></returns>
        public static IEstimator<ITransformer> BuildPipeline(MLContext mlContext)
        {
            // Data process configuration with pipeline data transformations
            var pipeline = mlContext.Transforms.Conversion.MapValueToKey(@"user_id", @"user_id")      
                                    .Append(mlContext.Transforms.Conversion.MapValueToKey(@"recipe_id", @"recipe_id"))      
                                    .Append(mlContext.Recommendation().Trainers.MatrixFactorization(approximationRank:8,numberOfIterations:20,learningRate:0.1F,labelColumnName:@"rating",matrixColumnIndexColumnName:@"user_id",matrixRowIndexColumnName:@"recipe_id"));

            return pipeline;
        }
    }
}
